# Kubernetes deployment for mlops-2.0
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops
  namespace: mlops
  labels:
    app: mlops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops
  template:
    metadata:
      labels:
        app: mlops
    spec:
      containers:
      - name: mlops
        #image: ghcr.io/koenraadva/mlops-2.0:sha-9014599
        image: ghcr.io/koenraadva/mlops-2.0:$GIT_SHA
        ports:
        - containerPort: 80
---
# NodePort service for mlops-2.0
apiVersion: v1
kind: Service
metadata:
  name: mlops
  namespace: mlops
spec:
  type: NodePort
  selector:
    app: mlops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
